services:
  - type: web
    name: guideon
    runtime: node
    buildCommand: npm install
    cacheDirectories:
      - node_modules
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
